apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 10.0.3.1-10.0.3.33
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-pool-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-pool